// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjT9hbiBBNUixDLPFsSbs--gZJIS__Ol4',
    appId: '1:903408976770:web:6e6d1a2896902084aa859b',
    messagingSenderId: '903408976770',
    projectId: 'food-recipe-b3870',
    authDomain: 'food-recipe-b3870.firebaseapp.com',
    storageBucket: 'food-recipe-b3870.firebasestorage.app',
    measurementId: 'G-5BCWHZ86GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgNGCLgPGmJm7BxaTDI3bC4WbgRA6xFk',
    appId: '1:903408976770:android:f151b9ad2f7fe5a4aa859b',
    messagingSenderId: '903408976770',
    projectId: 'food-recipe-b3870',
    storageBucket: 'food-recipe-b3870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ryU8eiKTD2BrBuJ8f3FoBBI5cgswOfQ',
    appId: '1:903408976770:ios:4906c927d1f2c730aa859b',
    messagingSenderId: '903408976770',
    projectId: 'food-recipe-b3870',
    storageBucket: 'food-recipe-b3870.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ryU8eiKTD2BrBuJ8f3FoBBI5cgswOfQ',
    appId: '1:903408976770:ios:4906c927d1f2c730aa859b',
    messagingSenderId: '903408976770',
    projectId: 'food-recipe-b3870',
    storageBucket: 'food-recipe-b3870.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjT9hbiBBNUixDLPFsSbs--gZJIS__Ol4',
    appId: '1:903408976770:web:750db753e620f95aaa859b',
    messagingSenderId: '903408976770',
    projectId: 'food-recipe-b3870',
    authDomain: 'food-recipe-b3870.firebaseapp.com',
    storageBucket: 'food-recipe-b3870.firebasestorage.app',
    measurementId: 'G-VY1TB57Z1B',
  );
}
